
spring:
  main:
    allow-bean-definition-overriding: true

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
  port: 8080
